export type Organization = {
  id: string;
  generated_id?: string | null;
  display_id?: string | null;
  name: string;
  slug?: string;
  abn?: string;
  acn?: string;
  business_type?: string;
  business_verification_status?: string;
  avg_org_rating?: string;
  brand_primary_color?: string;
  brand_secondary_color?: string;
  address?: string;
  contact_email?: string;
  contact_phone?: string;
  created_at?: string;
  is_verified?: boolean;
  licensed_staff_seats?: number;
  logo_url?: string;
  banner_url?: string;
  plan_id?: string | null;
  ranking_priority?: number;
  pending_properties_count?: number;
  builder_project_count?: number;
  pending_builder_projects_count?: number;
  stripe_customer_id?: string | null;
  state?: string;
  postcode?: string;
  latitude?: number | null;
  longitude?: number | null;
  type?: {
    id: string;
    name: string;
    slug: string;
    label?: string;
    module?: string | null;
    display_name?: string | null;
    capability_profile?: string | null;
    is_active?: boolean;
    sort_order?: number;
  };
  description?: string | null;
  website?: string | null;
  social_links?: Record<string, string>;
  service_areas?: string[];
  intro_video_url?: string | null;
  reel_urls?: string[];
};

export type OrganizationType = {
  id: string;
  name: string;
  label?: string;
  slug: string;
  module?: string | null;
  display_name?: string | null;
  capability_profile?: string | null;
  plan_family?: "property_owner" | "trades_professional" | "buyers_agent" | "builders" | null;
  is_active: boolean;
  sort_order: number;
};

export type OrganizationFormValues = {
  name: string;
  contact_email?: string;
  contact_phone?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  business_type?: "organisation" | "company" | "solo_trader";
  business_verification_status?: "pending" | "verified" | "rejected";
  abn?: string;
  acn?: string;
  is_verified?: boolean;
  profile_image?: File;
  banner_image?: File;
  description?: string;
  website?: string;
  social_links?: Record<string, string>;
  service_areas?: string[];
  intro_video_url?: string;
  reel_urls?: string[];
};

export type GetOrganizationParams = {
  page?: number;
  per_page?: number;
  search?: string;
  sort?: string;
  direction?: "asc" | "desc";
  filters?: Record<string, any>;
};
